name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1
        
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
      
    - name: Build
      run: bundle exec rake build

